name: Auto IP Collector

on:
  schedule:
    - cron: '0 */6 * * *' # 每6小时运行一次
  workflow_dispatch: # 允许手动触发Add commentMore actions
  push: # 允许提交触发

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: 🧠 Run IP collector script
        run: |
          python collect_ips.py

      - name: 📤 Commit and push IP results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # 如果有更改才提交
          git add ip.txt ipv6.txt
          git diff --cached --quiet || git commit -m "🤖 自动更新IP数据 $(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M')"
          git push
